-- Flyway V1 — initial schema.
-- Generated from the local dev database via pg_dump --schema-only.
-- From here on, every schema change is a new versioned migration (V2__, V3__, ...).

--
-- PostgreSQL database dump
--


-- Dumped from database version 16.11 (Debian 16.11-1.pgdg13+1)
-- Dumped by pg_dump version 16.11 (Debian 16.11-1.pgdg13+1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: public; Type: SCHEMA; Schema: -; Owner: -
--

-- *not* creating schema, since initdb creates it


--
-- Name: SCHEMA public; Type: COMMENT; Schema: -; Owner: -
--



SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: academy; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.academy (
    id uuid NOT NULL,
    address character varying(255),
    name character varying(255) NOT NULL
);


--
-- Name: academy_member; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.academy_member (
    belt character varying(255),
    belt_stripe integer,
    role character varying(255) NOT NULL,
    status smallint NOT NULL,
    academy_id uuid NOT NULL,
    user_id uuid NOT NULL,
    CONSTRAINT academy_member_belt_check CHECK (((belt)::text = ANY ((ARRAY['WHITE'::character varying, 'GRAY_WHITE'::character varying, 'GRAY'::character varying, 'GRAY_BLACK'::character varying, 'YELLOW_WHITE'::character varying, 'YELLOW'::character varying, 'YELLOW_BLACK'::character varying, 'ORANGE_WHITE'::character varying, 'ORANGE'::character varying, 'ORANGE_BLACK'::character varying, 'GREEN_WHITE'::character varying, 'GREEN'::character varying, 'GREEN_BLACK'::character varying, 'BLUE'::character varying, 'PURPLE'::character varying, 'BROWN'::character varying, 'BLACK'::character varying])::text[]))),
    CONSTRAINT academy_member_role_check CHECK (((role)::text = ANY ((ARRAY['STUDENT'::character varying, 'INSTRUCTOR'::character varying, 'MANAGER'::character varying, 'OWNER'::character varying])::text[]))),
    CONSTRAINT academy_member_status_check CHECK (((status >= 0) AND (status <= 2)))
);


--
-- Name: audit_log; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.audit_log (
    id bigint NOT NULL,
    academy_id uuid,
    action character varying(80) NOT NULL,
    actor_id uuid,
    ip_address character varying(45),
    occurred_at timestamp(6) with time zone NOT NULL,
    payload jsonb,
    resource_id character varying(80),
    resource_type character varying(40),
    user_agent text
);


--
-- Name: audit_log_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.audit_log_seq
    START WITH 1
    INCREMENT BY 50
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: class_attendance; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.class_attendance (
    id bigint NOT NULL,
    check_in_time timestamp(6) with time zone,
    status character varying(255) NOT NULL,
    scheduled_class_id bigint NOT NULL,
    student_id uuid NOT NULL,
    CONSTRAINT class_attendance_status_check CHECK (((status)::text = ANY ((ARRAY['REGISTERED'::character varying, 'CONFIRMED'::character varying, 'CANCELED'::character varying])::text[])))
);


--
-- Name: class_attendance_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.class_attendance ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.class_attendance_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: class_recurrence_rule; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.class_recurrence_rule (
    id uuid NOT NULL,
    day_of_week character varying(255) NOT NULL,
    start_time time(0) without time zone NOT NULL,
    template_id uuid NOT NULL,
    CONSTRAINT class_recurrence_rule_day_of_week_check CHECK (((day_of_week)::text = ANY ((ARRAY['MONDAY'::character varying, 'TUESDAY'::character varying, 'WEDNESDAY'::character varying, 'THURSDAY'::character varying, 'FRIDAY'::character varying, 'SATURDAY'::character varying, 'SUNDAY'::character varying])::text[])))
);


--
-- Name: class_template; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.class_template (
    id uuid NOT NULL,
    class_type character varying(255) NOT NULL,
    duration_minutes integer NOT NULL,
    name character varying(255) NOT NULL,
    training_type character varying(255) NOT NULL,
    academy_id uuid NOT NULL,
    instructor_id uuid NOT NULL,
    CONSTRAINT class_template_class_type_check CHECK (((class_type)::text = ANY ((ARRAY['REGULAR'::character varying, 'PRIVATE'::character varying, 'OPEN_MAT'::character varying, 'SEMINAR'::character varying, 'CAMP'::character varying, 'COMPETITION'::character varying, 'TEACHING'::character varying])::text[]))),
    CONSTRAINT class_template_training_type_check CHECK (((training_type)::text = ANY ((ARRAY['GI'::character varying, 'NO_GI'::character varying])::text[])))
);


--
-- Name: class_template_technique; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.class_template_technique (
    template_id uuid NOT NULL,
    technique_id bigint NOT NULL
);


--
-- Name: graduation_history; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.graduation_history (
    id bigint NOT NULL,
    graduation_date timestamp(6) with time zone NOT NULL,
    new_belt character varying(255) NOT NULL,
    new_belt_stripe integer,
    old_belt character varying(255),
    old_belt_stripe integer,
    academy_id uuid NOT NULL,
    promoted_by_id uuid NOT NULL,
    student_id uuid NOT NULL,
    CONSTRAINT graduation_history_new_belt_check CHECK (((new_belt)::text = ANY ((ARRAY['WHITE'::character varying, 'GRAY_WHITE'::character varying, 'GRAY'::character varying, 'GRAY_BLACK'::character varying, 'YELLOW_WHITE'::character varying, 'YELLOW'::character varying, 'YELLOW_BLACK'::character varying, 'ORANGE_WHITE'::character varying, 'ORANGE'::character varying, 'ORANGE_BLACK'::character varying, 'GREEN_WHITE'::character varying, 'GREEN'::character varying, 'GREEN_BLACK'::character varying, 'BLUE'::character varying, 'PURPLE'::character varying, 'BROWN'::character varying, 'BLACK'::character varying])::text[]))),
    CONSTRAINT graduation_history_old_belt_check CHECK (((old_belt)::text = ANY ((ARRAY['WHITE'::character varying, 'GRAY_WHITE'::character varying, 'GRAY'::character varying, 'GRAY_BLACK'::character varying, 'YELLOW_WHITE'::character varying, 'YELLOW'::character varying, 'YELLOW_BLACK'::character varying, 'ORANGE_WHITE'::character varying, 'ORANGE'::character varying, 'ORANGE_BLACK'::character varying, 'GREEN_WHITE'::character varying, 'GREEN'::character varying, 'GREEN_BLACK'::character varying, 'BLUE'::character varying, 'PURPLE'::character varying, 'BROWN'::character varying, 'BLACK'::character varying])::text[])))
);


--
-- Name: graduation_history_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.graduation_history ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.graduation_history_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: scheduled_class; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.scheduled_class (
    id bigint NOT NULL,
    class_type character varying(255) NOT NULL,
    duration_minutes integer NOT NULL,
    start_time timestamp(6) with time zone NOT NULL,
    status character varying(255) NOT NULL,
    training_type character varying(255) NOT NULL,
    academy_id uuid NOT NULL,
    instructor_id uuid NOT NULL,
    template_id uuid,
    reminder_sent_at timestamp(6) with time zone,
    CONSTRAINT scheduled_class_class_type_check CHECK (((class_type)::text = ANY ((ARRAY['REGULAR'::character varying, 'PRIVATE'::character varying, 'OPEN_MAT'::character varying, 'SEMINAR'::character varying, 'CAMP'::character varying, 'COMPETITION'::character varying, 'TEACHING'::character varying])::text[]))),
    CONSTRAINT scheduled_class_status_check CHECK ((((status)::text = ANY ((ARRAY['DRAFT'::character varying, 'PUBLISHED'::character varying, 'COMPLETED'::character varying, 'CANCELED'::character varying])::text[])) AND ((status)::text = ANY ((ARRAY['DRAFT'::character varying, 'PUBLISHED'::character varying, 'COMPLETED'::character varying, 'CANCELED'::character varying])::text[])))),
    CONSTRAINT scheduled_class_training_type_check CHECK (((training_type)::text = ANY ((ARRAY['GI'::character varying, 'NO_GI'::character varying])::text[])))
);


--
-- Name: scheduled_class_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.scheduled_class ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.scheduled_class_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: scheduled_class_technique; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.scheduled_class_technique (
    scheduled_class_id bigint NOT NULL,
    technique_id bigint NOT NULL
);


--
-- Name: technique; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.technique (
    id bigint NOT NULL,
    alternative_name character varying(255),
    name character varying(255) NOT NULL,
    target smallint NOT NULL,
    type smallint NOT NULL,
    CONSTRAINT technique_target_check CHECK (((target >= 0) AND (target <= 20))),
    CONSTRAINT technique_type_check CHECK (((type >= 0) AND (type <= 8)))
);


--
-- Name: technique_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.technique_seq
    START WITH 1
    INCREMENT BY 50
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: training; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.training (
    id bigint NOT NULL,
    cardio_rating integer,
    class_type character varying(255) NOT NULL,
    description character varying(255),
    duration_minutes integer NOT NULL,
    escapes integer NOT NULL,
    guard_passes integer NOT NULL,
    intensity_rating integer,
    rest_length_minutes integer NOT NULL,
    round_length_minutes integer NOT NULL,
    session_date timestamp(6) with time zone NOT NULL,
    submissions integer NOT NULL,
    sweeps integer NOT NULL,
    takedowns integer NOT NULL,
    taps integer NOT NULL,
    total_rolls integer NOT NULL,
    training_type character varying(255) NOT NULL,
    user_profile_id uuid NOT NULL,
    CONSTRAINT training_class_type_check CHECK (((class_type)::text = ANY ((ARRAY['REGULAR'::character varying, 'PRIVATE'::character varying, 'OPEN_MAT'::character varying, 'SEMINAR'::character varying, 'CAMP'::character varying, 'COMPETITION'::character varying, 'TEACHING'::character varying])::text[]))),
    CONSTRAINT training_training_type_check CHECK (((training_type)::text = ANY ((ARRAY['GI'::character varying, 'NO_GI'::character varying])::text[])))
);


--
-- Name: training_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.training_seq
    START WITH 1
    INCREMENT BY 50
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: training_submission_technique; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.training_submission_technique (
    training_id bigint NOT NULL,
    technique_id bigint NOT NULL
);


--
-- Name: training_submission_technique_allowed; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.training_submission_technique_allowed (
    training_id bigint NOT NULL,
    technique_id bigint NOT NULL
);


--
-- Name: training_technique; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.training_technique (
    training_id bigint NOT NULL,
    technique_id bigint NOT NULL
);


--
-- Name: user_profile; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.user_profile (
    id uuid NOT NULL,
    belt character varying(255),
    belt_stripe integer,
    name character varying(255) NOT NULL,
    nickname character varying(255) NOT NULL,
    role character varying(255),
    second_name character varying(255),
    starts_in date,
    anonymized_at timestamp(6) with time zone,
    photo_key character varying(255),
    photo_url character varying(255),
    email character varying(320),
    CONSTRAINT user_profile_belt_check CHECK (((belt)::text = ANY ((ARRAY['WHITE'::character varying, 'GRAY_WHITE'::character varying, 'GRAY'::character varying, 'GRAY_BLACK'::character varying, 'YELLOW_WHITE'::character varying, 'YELLOW'::character varying, 'YELLOW_BLACK'::character varying, 'ORANGE_WHITE'::character varying, 'ORANGE'::character varying, 'ORANGE_BLACK'::character varying, 'GREEN_WHITE'::character varying, 'GREEN'::character varying, 'GREEN_BLACK'::character varying, 'BLUE'::character varying, 'PURPLE'::character varying, 'BROWN'::character varying, 'BLACK'::character varying])::text[]))),
    CONSTRAINT user_profile_role_check CHECK (((role)::text = ANY ((ARRAY['CUSTOMER'::character varying, 'PLATFORM_MANAGER'::character varying, 'ADMIN'::character varying])::text[])))
);


--
-- Name: academy_member academy_member_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.academy_member
    ADD CONSTRAINT academy_member_pkey PRIMARY KEY (academy_id, user_id);


--
-- Name: academy academy_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.academy
    ADD CONSTRAINT academy_pkey PRIMARY KEY (id);


--
-- Name: audit_log audit_log_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.audit_log
    ADD CONSTRAINT audit_log_pkey PRIMARY KEY (id);


--
-- Name: class_attendance class_attendance_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.class_attendance
    ADD CONSTRAINT class_attendance_pkey PRIMARY KEY (id);


--
-- Name: class_recurrence_rule class_recurrence_rule_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.class_recurrence_rule
    ADD CONSTRAINT class_recurrence_rule_pkey PRIMARY KEY (id);


--
-- Name: class_template class_template_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.class_template
    ADD CONSTRAINT class_template_pkey PRIMARY KEY (id);


--
-- Name: graduation_history graduation_history_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.graduation_history
    ADD CONSTRAINT graduation_history_pkey PRIMARY KEY (id);


--
-- Name: scheduled_class scheduled_class_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.scheduled_class
    ADD CONSTRAINT scheduled_class_pkey PRIMARY KEY (id);


--
-- Name: technique technique_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.technique
    ADD CONSTRAINT technique_pkey PRIMARY KEY (id);


--
-- Name: training training_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.training
    ADD CONSTRAINT training_pkey PRIMARY KEY (id);


--
-- Name: user_profile ukm9ga0crhcge7onj1gx9a5lnjy; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_profile
    ADD CONSTRAINT ukm9ga0crhcge7onj1gx9a5lnjy UNIQUE (nickname);


--
-- Name: class_attendance ukq21vr66o2rhmao1ns9q3ffm6l; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.class_attendance
    ADD CONSTRAINT ukq21vr66o2rhmao1ns9q3ffm6l UNIQUE (scheduled_class_id, student_id);


--
-- Name: user_profile user_profile_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_profile
    ADD CONSTRAINT user_profile_pkey PRIMARY KEY (id);


--
-- Name: idxfnnk3h6ilvb4iaj542amh62tc; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idxfnnk3h6ilvb4iaj542amh62tc ON public.audit_log USING btree (academy_id, occurred_at DESC);


--
-- Name: idxwptep7d59ws0r3oygjun1fsf; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idxwptep7d59ws0r3oygjun1fsf ON public.audit_log USING btree (actor_id, occurred_at DESC);


--
-- Name: training_submission_technique fk19i3ss86rajmk06toq221jh6k; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.training_submission_technique
    ADD CONSTRAINT fk19i3ss86rajmk06toq221jh6k FOREIGN KEY (technique_id) REFERENCES public.technique(id);


--
-- Name: training_submission_technique_allowed fk1xj4ca1yow0hdn1ybrvect17b; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.training_submission_technique_allowed
    ADD CONSTRAINT fk1xj4ca1yow0hdn1ybrvect17b FOREIGN KEY (training_id) REFERENCES public.training(id);


--
-- Name: graduation_history fk3pt3dymhorwc0es9lf0dduwg; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.graduation_history
    ADD CONSTRAINT fk3pt3dymhorwc0es9lf0dduwg FOREIGN KEY (academy_id) REFERENCES public.academy(id);


--
-- Name: class_template_technique fk433tbr33fc7cduqqvnk7ljye0; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.class_template_technique
    ADD CONSTRAINT fk433tbr33fc7cduqqvnk7ljye0 FOREIGN KEY (template_id) REFERENCES public.class_template(id);


--
-- Name: scheduled_class_technique fk4t911de0i9qkw41ggasoi96y; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.scheduled_class_technique
    ADD CONSTRAINT fk4t911de0i9qkw41ggasoi96y FOREIGN KEY (technique_id) REFERENCES public.technique(id);


--
-- Name: class_attendance fk56iru1abbadr67rardfhtplaj; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.class_attendance
    ADD CONSTRAINT fk56iru1abbadr67rardfhtplaj FOREIGN KEY (student_id) REFERENCES public.user_profile(id);


--
-- Name: graduation_history fk5tsel9r6686igqn73r6klecd0; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.graduation_history
    ADD CONSTRAINT fk5tsel9r6686igqn73r6klecd0 FOREIGN KEY (promoted_by_id) REFERENCES public.user_profile(id);


--
-- Name: training_technique fk621n29pnxq2u7unytohf0g4gq; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.training_technique
    ADD CONSTRAINT fk621n29pnxq2u7unytohf0g4gq FOREIGN KEY (technique_id) REFERENCES public.technique(id);


--
-- Name: training_technique fk6pn3b6ijuabkob64l8ofyxcrq; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.training_technique
    ADD CONSTRAINT fk6pn3b6ijuabkob64l8ofyxcrq FOREIGN KEY (training_id) REFERENCES public.training(id);


--
-- Name: scheduled_class fk6xjcbklyq0cnlh4drf229rhbr; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.scheduled_class
    ADD CONSTRAINT fk6xjcbklyq0cnlh4drf229rhbr FOREIGN KEY (academy_id) REFERENCES public.academy(id);


--
-- Name: class_template fk7x3k8k3a1g8ixf2ngp80i51vb; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.class_template
    ADD CONSTRAINT fk7x3k8k3a1g8ixf2ngp80i51vb FOREIGN KEY (instructor_id) REFERENCES public.user_profile(id);


--
-- Name: scheduled_class_technique fkc2r8mrkmo8p0175tdpjhg1f6g; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.scheduled_class_technique
    ADD CONSTRAINT fkc2r8mrkmo8p0175tdpjhg1f6g FOREIGN KEY (scheduled_class_id) REFERENCES public.scheduled_class(id);


--
-- Name: training fkc31m3aj5md3q144ft06rju827; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.training
    ADD CONSTRAINT fkc31m3aj5md3q144ft06rju827 FOREIGN KEY (user_profile_id) REFERENCES public.user_profile(id);


--
-- Name: scheduled_class fkd2h0bba2db5benmy6inhq4vy1; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.scheduled_class
    ADD CONSTRAINT fkd2h0bba2db5benmy6inhq4vy1 FOREIGN KEY (template_id) REFERENCES public.class_template(id);


--
-- Name: academy_member fkdkwqx8ic89hkfx2ktoooaxac4; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.academy_member
    ADD CONSTRAINT fkdkwqx8ic89hkfx2ktoooaxac4 FOREIGN KEY (user_id) REFERENCES public.user_profile(id);


--
-- Name: scheduled_class fkeij6dau44idsenl5qffrrgnjt; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.scheduled_class
    ADD CONSTRAINT fkeij6dau44idsenl5qffrrgnjt FOREIGN KEY (instructor_id) REFERENCES public.user_profile(id);


--
-- Name: graduation_history fkgpud94c847uu79h804ee00yxn; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.graduation_history
    ADD CONSTRAINT fkgpud94c847uu79h804ee00yxn FOREIGN KEY (student_id) REFERENCES public.user_profile(id);


--
-- Name: academy_member fkjio4twv4oasil1sr469y8rhq9; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.academy_member
    ADD CONSTRAINT fkjio4twv4oasil1sr469y8rhq9 FOREIGN KEY (academy_id) REFERENCES public.academy(id);


--
-- Name: class_attendance fkljne2apn77twv19dft9m5mcgc; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.class_attendance
    ADD CONSTRAINT fkljne2apn77twv19dft9m5mcgc FOREIGN KEY (scheduled_class_id) REFERENCES public.scheduled_class(id);


--
-- Name: class_template_technique fkm11jc7skfjvn2guvsrr7p6gqh; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.class_template_technique
    ADD CONSTRAINT fkm11jc7skfjvn2guvsrr7p6gqh FOREIGN KEY (technique_id) REFERENCES public.technique(id);


--
-- Name: training_submission_technique_allowed fkme4ffd475oohlby4ws76xj9wy; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.training_submission_technique_allowed
    ADD CONSTRAINT fkme4ffd475oohlby4ws76xj9wy FOREIGN KEY (technique_id) REFERENCES public.technique(id);


--
-- Name: class_template fkmhe0dtxhx50ooehuf1dgy8uyk; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.class_template
    ADD CONSTRAINT fkmhe0dtxhx50ooehuf1dgy8uyk FOREIGN KEY (academy_id) REFERENCES public.academy(id);


--
-- Name: training_submission_technique fknqq0awh8fyt7b102jnemtrhst; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.training_submission_technique
    ADD CONSTRAINT fknqq0awh8fyt7b102jnemtrhst FOREIGN KEY (training_id) REFERENCES public.training(id);


--
-- Name: class_recurrence_rule fko1r3eq3fnmuke5axncp2vylg2; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.class_recurrence_rule
    ADD CONSTRAINT fko1r3eq3fnmuke5axncp2vylg2 FOREIGN KEY (template_id) REFERENCES public.class_template(id);


--
-- PostgreSQL database dump complete
--


